### ISSUE TITLE
Centroided data is not supported for peak picking operations

### ISSUE THREAD

**Issue by thomas-enzlein** [m2aia/m2aia#31]
When you (accidentally) click on the peak picking widget you get a warning saying: 
"Centroided data is not supported for peak picking operations" 
 The problem is that you will get this warning for every centroided data set that is currently open. In case of 3D reconstruction tasks this can easily be 50 or more data sets.

A single warning would be more then enough or only display the warning when the user wants to start the peak picking on a specific data set and not on entering the peak picking widget.

**Comment by jtfcordes** [comment]
Thanks for this hint.
The warning was removed. Please check the latest version of M²aia. 
Centroids are now concidered as picked peaks.
