### ISSUE TITLE
m2aia on MacOS; MITK-Configure error

### ISSUE THREAD

**Issue by Elle-hu** [m2aia/m2aia#33]
Hi!

I am trying to build m2aia on a MacBook Pro laptop (with MacOS Ventura 13.2.1). Is the Linux version compatible with this system?

So far I managed to generate the build files with Cmake using Unix Make file as generator.
In the terminal I then run:

cmake --build path/to/m2aia/build

where "path/to/m2aia/build" is the same path specified in the cmake GUI in 'Where to build the binaries” and containing the build directory created in the m2aia folder.

Everything run smoothly for a couple but the process does not get completed ending with:

```
-- Configuring incomplete, errors occurred!
make[2]: *** [ep/src/MITK-Configure-stamp/MITK-Configure-configure] Error 1
make[1]: *** [CMakeFiles/MITK-Configure.dir/all] Error 2
make: *** [all] Error 2

```

Scrolling up I see several error messages, related to  mitkMacroCreateModuleTests, such as :

```
CMake Error at CMake/mitkMacroCreateModuleTests.cmake:53 (set_property):
  set_property could not find TARGET MitkRTTestDriver.  Perhaps it has not
  yet been created.
Call Stack (most recent call first):
  Modules/RT/test/CMakeLists.txt:1 (MITK_CREATE_MODULE_TESTS)
```

or to mitkFunctionCreatePlugin (several errors in this case, almost all pointing to  missing" MitkQtWidgetsExt", such as:

```
CMake Error at CMake/mitkFunctionCreatePlugin.cmake:80 (message):
  org_mitk_gui_qt_datamanager is missing requirements and won't be built.
  Missing: MitkQtWidgetsExt
Call Stack (most recent call first):
  Plugins/org.mitk.gui.qt.datamanager/CMakeLists.txt:3 (mitk_create_plugin)


CMake Error at CMake/mitkFunctionCreatePlugin.cmake:80 (message):
  org_mitk_gui_qt_properties is missing requirements and won't be built.
  Missing: MitkQtWidgetsExt
Call Stack (most recent call first):
  Plugins/org.mitk.gui.qt.properties/CMakeLists.txt:3 (mitk_create_plugin)


CMake Error at CMake/mitkFunctionCreatePlugin.cmake:80 (message):
  org_mitk_gui_qt_basicimageprocessing is missing requirements and won't be
  built.  Missing: MitkQtWidgetsExt;MitkMapperExt
Call Stack (most recent call first):
  Plugins/org.mitk.gui.qt.basicimageprocessing/CMakeLists.txt:3 (mitk_create_plugin)


CMake Error at CMake/mitkFunctionCreatePlugin.cmake:80 (message):
  org_mitk_gui_qt_dicombrowser is missing requirements and won't be built.
  Missing: MitkContourModel;MitkQtWidgetsExt
Call Stack (most recent call first):
  Plugins/org.mitk.gui.qt.dicombrowser/CMakeLists.txt:23 (mitk_create_plugin)
```

I have to specify I have not installed MITK independently, I understood that it would have been built with the codes for m2aia. Is that correct? 
How should I proceed to succesfully complete the building of m2aia (if it is at all possible in a MacOS system)?

Thanks!

**Comment by jtfcordes** [comment]
Hey!

as the MITK documentation (https://docs.mitk.org/2023.04/SupportedPlatformsPage.html) indicates, this particular version is not supported - in principle it could work:

- It would be helpful to have the complete output of the cmake/build process.

- Check the MITK build instructions (https://docs.mitk.org/2023.04/BuildInstructionsPage.html) and try to bild MITK without m2aia (MITK_EXTENSION_DIRS=<EMPTY!>). Start the new build in a clean directory. Once the MITK build works, m2aia can be added to the build process in a subsequent step (MITK_EXTENSION_DIRS=<Path/To/M2aia>).
To be actually sure that MITK is compatible with your system. It would be worth it to go an additional step back and try to build the orignal MITK first. This can be done by checking out https://github.com/mitk/mitk/tree/v2023.04.

- The MitkQtWidgetsExt build problems could be related to a Qt version mismatch. Check that you use the correct version of Qt (a version that works is ie. Qt version 5.15.3). 

"I have to specify I have not installed MITK independently, I understood that it would have been built with the codes for m2aia. Is that correct?" 

Yes, this is correct. You build a custom MITK version to be compatible to the M2aia code.
https://github.com/m2aia/mitk @branch m2aia-main

I believe this is the first attempt to build m2aia on a macOS system - at least from what I know.

Thank you for the report!
